version: '3'
services:
  mysql-db:
    image: mysql:5.7
    hostname: mysql-db
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: 'show_time'
      MYSQL_USER: 'martin'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3306:3306'
    volumes:
      - my-db-volume:/var/lib/mysql
volumes:
  my-db-volume:
